name: cv-project
channels: 
  - conda-forge
  - defaults
dependencies: 
  - python=3.10.9
  - pip
  - matplotlib=3.7.1
  - scikit-learn=1.3.0
  - numpy=1.23.3
  - pandas=2.2.3
  - imutils=0.5.4 
  - pip: 
    - cv2-enumerate-cameras==1.1.17
    - gradio==5.8.0
