name: folo
channels: 
  - conda-forge
  - defaults
dependencies: 
  - python=3.10.9
  - pip=24.3.1
  - scikit-learn=1.3.0
  - numpy=1.23.3
  - pandas=2.2.3
  - pip: 
    - opencv-python==4.10.0.84
    - opencv-contrib-python==4.10.0.84
    - imutils==0.5.4
    - matplotlib==3.7.1
    - gradio==5.8.0
